### ISSUE TITLE
/pixelcenter set @p from a command block doesn't set the nearest node most of the time

### ISSUE THREAD

**Issue by kittenchilly** [salmjak/PixelCenter#2]
Even if the node is literally right next to where the /pixelcenter set is being done, it just doesn't work. Turning off ranges reveals that it actually skips over the nearest node and finds the next nearest node (which can be really far away). This makes this sidemod impractical for any actual adventure maps because it just doesn't work.

**Comment by salmjak** [comment]
Try the new [release](https://github.com/salmjak/PixelCenter/releases)

I had derped in the loop to find the nearest node. I have no idea how this worked for me before. Thanks for reporting this.
